[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[rpc_endpoints]
bsc_testnet = "${BSC_TESTNET_RPC}"
localhost = "http://127.0.0.1:8545"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api", chain = 97 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
